version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: python:3.12
    container_name: fastapi_backend
    command: >
      /bin/sh -c "chmod +x wait-for-it.sh && ./wait-for-it.sh db:5432 &&
                  pip install -r requirements.txt &&
                  alembic upgrade head &&
                  uvicorn rest.app:app --host 0.0.0.0 --port 8090"
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      CLEAN_ENV: PROD  # Additional environment variable
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - "8090:8090"

volumes:
  postgres_data:
